# This is the name of workflow that will be display in the Action tab
name: cicd

# Manual click (deliver) workflow whenever user need

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
# every job needs seperate runner called parrarelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        run: echo "clone the code from github"


  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build the container
        run: echo " build the docker container"
        


  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "test the container"
        



  deploy:
    if: inputs.environment == 'dev'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo " docker compose deploy the app"

    
        
