---
name: Hello
# Runs on trigger
on:
  push:
    branches: [main]

    path:
      - '**.html'
# There are jobs inside workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello to users
        run: echo "Hello dosto"
      - name: say Hello to username
        run: echo "Hello $USER"
  details:
    runs-on: ubuntu-latest 
    steps:
      - name: show what is the versions of python & docker
        run: docker --version && python --version
