---
name: Hello
on:
  push:
    branches: [main]
# There are jobs inside workflow
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello to users
        run: echo "Hello dosto"
      - name: say Hello to username
        run: echo "Hello $USER"
